.PHONY: clean All

All:
	@echo "----------Building project:[ Sockets - Debug ]----------"
	@$(MAKE) -f  "Sockets.mk"
clean:
	@echo "----------Cleaning project:[ Sockets - Debug ]----------"
	@$(MAKE) -f  "Sockets.mk" clean
