.PHONY: clean All

All:
	@echo "----------Building project:[ Sockets21 - Debug ]----------"
	@$(MAKE) -f  "Sockets21.mk"
clean:
	@echo "----------Cleaning project:[ Sockets21 - Debug ]----------"
	@$(MAKE) -f  "Sockets21.mk" clean
